In [23]:
import numpy as np
arr=np.array([[1,2],[3,4]])

eig_val, eig_vec=np.linalg.eig(arr)
det=np.linalg.det(arr)

print("Eigenvalues:  \n",eig_val)
print("\nEigenvectors: \n",eig_vec)
print("\nDeterminant: \n",det)

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
cross=np.cross(vec1,vec2)
print("\nCross product: \n",cross)

coefficients = np.array([[1, 2, -2], [2, 1, -5], [1, -4, 1]])
constants = np.array([[-15], [-21], [18]])

solution = np.linalg.solve(coefficients, constants)

print("\nSolution: \n",solution)

Eigenvalues:  
 [-0.37228132  5.37228132]

Eigenvectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Determinant: 
 -2.0000000000000004

Cross product: 
 [-3  6 -3]

Solution: 
 [[-1.]
 [-4.]
 [ 3.]]
